"""
Render the config into the read to run dag
"""
from typing import Dict, Any
from datetime import datetime

import jinja2


DAG_TEMPLATE = jinja2.Template(
    """
'''
Generated by Airflow Datalake! Do not edit!
Timestamp {{ timestamp }}

If your have problem with google cloud account permissions,
make sure you include your team email.
Check detail at https://docs.google.com/spreadsheets/d/1Lsal8SDy8Np_8BNbgeou-rEzZfKv5qXIgHeGaLxNm5Q
'''

from airflow import DAG

from airlake.dynamic.render import render

conf = {{ json_conf }}
name = '{{ name }}'
render(globals(), name, conf)"""
)




def dump_to_py(name: str, conf: Dict[str, Any]):
    """Dumps configs from dict into python dag file"""
    return DAG_TEMPLATE.render(
        name=name,
        json_conf=conf,
        timestamp=datetime.now().astimezone().isoformat(),
    )
